/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.controladores.Vehiculobd;
import com.istloja.modelTable.ComunicacionVistaModelosTablas;
import com.istloja.modelo.Vehiculo;
import com.istloja.modelTable.ModelTableListar;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Jorge Kng
 */
public class Listar extends javax.swing.JDialog implements ComunicacionVistaModelosTablas{
    ModelTableListar modeloTablaListar;
    
    Vehiculobd controladorVehiculo;
    
    
    
    /**
     * Creates new form NewJDialog
     */
    public Listar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        controladorVehiculo = new Vehiculobd();
        modeloTablaListar = new ModelTableListar(controladorVehiculo.obtenerVehiculos(),this);
        
        initComponents();
        rbDentroParq.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPlacaB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPropietarioB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateFechaB = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBq = new javax.swing.JButton();
        btnCierre = new javax.swing.JButton();
        cbMoto = new javax.swing.JCheckBox();
        cbAuto = new javax.swing.JCheckBox();
        rbDentroParq = new javax.swing.JRadioButton();
        rbFueraParq = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Lista de Vehículos");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tipo de Vehículo ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Placa");

        txtPlacaB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre del Propietario");

        txtPropietarioB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Estado");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Fecha");

        dateFechaB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTable1.setModel(modeloTablaListar);
        jScrollPane1.setViewportView(jTable1);

        btnBq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/img/buskar.png"))); // NOI18N
        btnBq.setText("Buscar ");
        btnBq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBqActionPerformed(evt);
            }
        });

        btnCierre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/istloja/img/kalkulars.png"))); // NOI18N
        btnCierre.setText("Cierre");
        btnCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreActionPerformed(evt);
            }
        });

        cbMoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbMoto.setText("Motocicleta");

        cbAuto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbAuto.setText("Automóvil");

        rbDentroParq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbDentroParq.setText("Dentro del Parqueadero");
        rbDentroParq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDentroParqActionPerformed(evt);
            }
        });

        rbFueraParq.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbFueraParq.setText("Fuera del Parqueadero");
        rbFueraParq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFueraParqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtPlacaB, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbMoto)
                                .addGap(18, 18, 18)
                                .addComponent(cbAuto)
                                .addGap(76, 76, 76)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbDentroParq)
                                    .addComponent(rbFueraParq))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPropietarioB, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(dateFechaB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addGap(164, 164, 164)))
                                .addComponent(btnBq))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(btnCierre)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlacaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPropietarioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBq)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateFechaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(cbMoto)
                            .addComponent(cbAuto))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(rbDentroParq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbFueraParq)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCierre)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBqActionPerformed
        // TODO add your handling code here:
        Vehiculo vehiculo = new Vehiculo();
        vehiculo.setPlaca(txtPlacaB.getText());
        vehiculo.setPropietario(txtPropietarioB.getText());
        
        if (cbAuto.isSelected()) {
            if (cbMoto.isSelected()) {
                vehiculo.setTipo_Vehiculo("");;
            } else {
                vehiculo.setTipo_Vehiculo("Automovil");
            }
        } else if (cbMoto.isSelected()) {
            vehiculo.setTipo_Vehiculo("Motocicleta");
        }
        if(rbDentroParq.isSelected()){
            vehiculo.setEstado("Disponible");
        }

        if (rbFueraParq.isSelected()) {
           
            vehiculo.setEstado("No Disponible");
        }
       
        
        if (dateFechaB.getDate() != null) {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = dateFechaB.getDate();
            String date1 = dateFormat.format(date);
            vehiculo.setHora_Entrada(date1);
        }
        
        
        System.out.println(controladorVehiculo.BuscarVehiculo(vehiculo));
        
        modeloTablaListar.setVehiculosbusq(controladorVehiculo.BuscarVehiculo(vehiculo));
        modeloTablaListar.fireTableDataChanged();
    }//GEN-LAST:event_btnBqActionPerformed

    private void rbDentroParqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDentroParqActionPerformed
        // TODO add your handling code here:
        if (rbDentroParq.isSelected()) {
            rbFueraParq.setSelected(false);
        } 
    }//GEN-LAST:event_rbDentroParqActionPerformed

    private void rbFueraParqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFueraParqActionPerformed
        // TODO add your handling code here:
        if (rbFueraParq.isSelected()) {
            rbDentroParq.setSelected(false);
            
        }
    }//GEN-LAST:event_rbFueraParqActionPerformed

    private void btnCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreActionPerformed
        // TODO add your handling code here:
        Vehiculo vehiculo = new Vehiculo();
        vehiculo.setPlaca(txtPlacaB.getText());
        vehiculo.setPropietario(txtPropietarioB.getText());
        
        if (cbAuto.isSelected()) {
            if (cbMoto.isSelected()) {
                vehiculo.setTipo_Vehiculo("");;
            } else {
                vehiculo.setTipo_Vehiculo("Automovil");
            }
        } else if (cbMoto.isSelected()) {
            vehiculo.setTipo_Vehiculo("Motocicleta");
        }
        if(rbDentroParq.isSelected()){
            vehiculo.setEstado("Disponible");
        }

        if (rbFueraParq.isSelected()) {
           
            vehiculo.setEstado("No Disponible");
        }
       
        
        if (dateFechaB.getDate() != null) {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = dateFechaB.getDate();
            String date1 = dateFormat.format(date);
            vehiculo.setHora_Entrada(date1);
        }
        controladorVehiculo.Total(vehiculo);
    }//GEN-LAST:event_btnCierreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Listar dialog = new Listar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBq;
    private javax.swing.JButton btnCierre;
    private javax.swing.JCheckBox cbAuto;
    private javax.swing.JCheckBox cbMoto;
    private com.toedter.calendar.JDateChooser dateFechaB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbDentroParq;
    private javax.swing.JRadioButton rbFueraParq;
    private javax.swing.JTextField txtPlacaB;
    private javax.swing.JTextField txtPropietarioB;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param v
     */
    int contadorClick = 0;
    boolean ejecutar;

    @Override
    public void clickVehiculo(Vehiculo v) {
        ejecutar = true;
        //HILO DE PROGRMACIÓN
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (ejecutar) {
                    try {
                        //Parar un segundo
                        Thread.sleep(400);
                        contadorClick = 0;
                        ejecutar = false;
                        System.out.println("Reinicia CLICK");
                    } catch (InterruptedException e) {
                        System.out.println(e.getMessage());
                    }
                }
            }
        }).start();

        contadorClick++;
        if (contadorClick == 2) {
            if (JOptionPane.showConfirmDialog(rootPane, "Se eliminará el item, ¿desea continuar?",
                    "Eliminar Producto", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    controladorVehiculo.EliminarVehiculo(v);
                    modeloTablaListar.setVehiculosbusq(controladorVehiculo.obtenerVehiculos());
                    modeloTablaListar.fireTableDataChanged();
            }
        }
    }

}
